import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>fashion.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <img src="/c.jpg" alt="" className="mx-auto block" />
      </div>
    </div>
  );
}
